name: hts-ai-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - aiohappyeyeballs
    - aiohttp
    - aiosignal
    - annotated-types
    - anyio
    - attrs
    - certifi
    - charset-normalizer
    - click
    - colorama
    - dataclasses-json
    - distro
    - faiss-cpu
    - fastapi
    - filelock
    - frozenlist
    - fsspec
    - gitdb
    - GitPython
    - greenlet
    - gritql
    - h11
    - httpcore
    - httpx
    - httpx-sse
    - huggingface-hub
    - idna
    - Jinja2
    - jiter
    - joblib
    - jsonpatch
    - jsonpointer
    - langchain
    - langchain-cli
    - langchain-community
    - langchain-core
    - langchain-huggingface
    - langchain-text-splitters
    - langserve
    - langsmith
    - markdown-it-py
    - MarkupSafe
    - marshmallow
    - mdurl
    - mpmath
    - multidict
    - mypy_extensions
    - networkx
    - numpy
    - openai
    - orjson
    - packaging
    - pandas
    - pillow
    - propcache
    - pydantic
    - pydantic-settings
    - pydantic_core
    - Pygments
    - pypdf
    - PyPDF2
    - python-dateutil
    - python-dotenv
    - pytz
    - PyYAML
    - regex
    - requests
    - requests-toolbelt
    - rich
    - safetensors
    - scikit-learn
    - scipy
    - sentence-transformers
    - setuptools
    - shellingham
    - six
    - smmap
    - sniffio
    - SQLAlchemy
    - sse-starlette
    - starlette
    - sympy
    - tenacity
    - threadpoolctl
    - tokenizers
    - tomlkit
    - torch
    - tqdm
    - transformers
    - typer
    - typing-inspect
    - typing-inspection
    - typing_extensions
    - tzdata
    - urllib3
    - uvicorn
    - wheel
    - yarl
    - zstandard